development:
  instance_details:
    description_column: :description
    user_method: :user
    screenshot_column: :screenshot
    url_column: :url
  ticket_details:
    repo: "test_repo"
    labels: ["user_issue"]
    issue_title: "Found a bug in BuildMyLoads"
  s3_details:
    bucket: "test-bucket"
    region: "test-region"
test:
  instance_details:
    description_column: :description
    user_method: :user
    screenshot_column: :screenshot
    url_column: :url
  ticket_details:
    repo: "test_repo"
    labels: ["user_issue"]
    issue_title: "Found a bug in BuildMyLoads"
  s3_details:
    bucket: "test-bucket"
    region: "test-region"
